version: '3'

services:
  ui:
    image: 'ui:latest'
    container_name: 'ui'
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - './src:/app/src'
    ports:
      - '80:5173'
    command: '--host'